teacher(dinesh).
teacher(latika).
teacher(alpana).
teacher(antim).
teacher(samridhi).
subject(ai).
subject(ml1).
subject(ml2).
subject(cd).
subject(cn).
teaches(dinesh,ai).
teaches(latika,ml1).
teaches(alpana,ml2).
teaches(antim,cn).
teaches(samridhi,cd).
student(aditya).
student(harshiq).
student(abhay).
student(yash).
student(kunal).
opted(aditya,ai).
opted(aditya,ml1).
opted(aditya,cd).
opted(harshiq,ai).
opted(harshiq,ml2).
opted(harshiq,cd).
opted(abhay,ai).
opted(abhay,ml1).
opted(abhay,cn).
opted(yash,ml1).
opted(yash,cd).
opted(kunal,ml1).
opted(kunal,cn).
guide(X,Y):- teaches(X,Z),opted(Y,Z). 